#The webserver plugin cofiguration file.
[webserver]
#This will specify the ip adress of the machine that the server is running on. I would recomend to change it as some pages might 404 if you dont.
ip=0.0.0.0

#The port to listen on.
port=5000

#Section related to security and .key, .crt file locations. Its really recomended to use ssl if you are exposing the web interface to the internet.
[SSL]
userssl=False
crt="certs/certificate.crt"
key="certs/private.key"
